config:
  train:
    batch_size: 256
    shuffle: True
    num_workers: 4

  val:
    batch_size: 256
    shuffle: False
    num_workers: 4

  test:
    batch_size: 32
    shuffle: False
    num_workers: 4
  
  lr: 0.001
  num_epochs: 50
